<?php

/**
 * Created by PhpStorm.
 * User: Михаил
 * Date: 2/11/2020
 * Time: 1:53 PM
 */
Class Model_Product extends Model
{
    public $id;
    public $title;
    public $price;



    function find($columnValue = [])
    {
        $table = $this->getClassName(); // TODO: Change the autogenerated stub
        $sql = sql::select($table, $columnValue);
        //TODO: $sql = sql::selectOne($table, $columnValue);
        //de(sql::select($table,$columnValue));

        //todo USE $this->load($sql)
        return $sql;
    }

    function load($fieldData = null)
    {
        // заполняем значения разбивая массив
        foreach ($fieldData as $key => $value) {
            $this->$key = $value;
        }
    }

    function save($updateValue = null)
    {
        $fieldValue = $this->get_object_mass();

        $table = $this->getClassName();

        if (is_null($fieldValue['id'])) {
            array_shift($fieldValue);
            $insertId= sql::insert($table, $fieldValue);
            $this->load($fieldValue);
            $this->id = $insertId;
        } elseif ($fieldValue['id']) {
            sql::update($table,$updateValue, $fieldValue);
            $this->load($updateValue);
        } else {
            return false;
        }
    }

    function get_object_mass()
    {
        $mass = get_object_vars($this);
        return $mass;
    }


}

/*

1. Перевести регистрацию и авторизацию на модели


 */




