<?php

/**
 * Created by PhpStorm.
 * User: Михаил
 * Date: 2/11/2020
 * Time: 1:53 PM
 */
Class Model_Product extends Model
{
    public $id;
    public $title;
    public $price;

    function find($columnValue = [])
    {
        //de($columnValue);
        $table = $this->getClassName(); // TODO: Change the autogenerated stub
        $mass = sql::select($table, $columnValue);
        return $mass;
    }

    function load($fieldData = null)
    {
        // заполняем значения разбивая массив
        foreach ($fieldData as $key => $value) {
            $this->$key = $value;
        }
    }

    function save($data = null)
    {
        $fieldValue = $this->get_object_mass();
        $table = $this->getClassName();
        if ($data == 'update') {
            $mass = sql::update($table, $fieldValue, $fieldValue);
            return $mass;
        } elseif ($data == 'insert') {
            $mass = sql::insert($table, $fieldValue);
            return $mass;
        } else {
            return false;
        }
    }

    function get_object_mass()
    {
        $mass = get_object_vars($this);
        array_shift($mass);
        return $mass;
    }


}






